title: Vinod Jaiswal
description: Technologist | Engineering Manager | Software Architect
google_analytics: jpos, vinod jaiswal, vinod, jaiswal, vinod-jaiswal18, vj, java, payment switch
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions